spring:
  datasource:
    url: jdbc:h2:mem:solutionv2produccion
    driverClassName: org.h2.Driver
    username: postgres
    password: system
  jpa:
    hibernate:
      ddl-auto: update
  eureka:
    client:
      enabled: false
