name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create --subnet=192.168.18.0/24 my_network

      - name: Run postgresSql container
        run: |
          docker run -d --name postgres \
          --network my_network \
          --ip 192.168.18.164 \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=system \
          -e POSTGRES_DB=solutionv2produccion \
          -p 5432:5432 \
          postgres:15.0

      - name: Run Eureka container
        run: |
          docker run -d --name eureka \
          --network my_network \
          --ip 192.168.10.35 \
          -e EUREKA_CLIENT_REGISTER_WITH_EUREKA=false \
          -e EUREKA_CLIENT_FETCH_REGISTRY=false \
          -p 6666:6666 \
          desarrollohusjp/eurekaserver-image

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -Dspring.profiles.active=dev

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/microservices:mesaprosesos-image .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/microservices:mesaprosesos-image